services:
  app:
    build: .
    container_name: pro-monoclan-app
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    user: "node"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp